server:
  port: 9010
spring:
  application:
    name: blocker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}
  cloud:
    consul:
      enabled: false
management:
  zipkin:
    tracing:
      endpoint:  ${ZIPKIN_ENDPOINT}
  tracing:
    enabled: true
    sampling:
      probability: 1 # Сэмплируем все запросы