server:
  port: 9010
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: blocker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${keycloak_url}/realms/bank/protocol/openid-connect/certs
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
      config:
        enabled: false