version: '3'
networks:
  app-net:
    driver: bridge
services:
  postgres:
    image: postgres:17
    container_name: postgres
    env_file: ".env"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-net