version: '3'
networks:
  app-net:
    driver: bridge
services:
  postgres:
    image: postgres:17
    container_name: postgres
    env_file: ".env"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./db.init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./storage/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-net
  keycloak:
    platform: linux/amd64
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: 'keycloak'
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./storage/keycloak:/opt/keycloak/data/import
    networks:
      - app-net
  consul:
    image: consul:1.15.4
    container_name: 'consul'
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      - app-net
  consul-server:
    image: consul:1.15.4
    container_name: 'consul-server'
    networks:
      - app-net
    volumes:
      - ./storage/consul:/consul/data
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
  consul-agent:
    image: consul:1.15.4
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      - app-net