version: '3'
networks:
  app-net:
    driver: bridge
services:
  postgres:
    image: postgres:17
    container_name: postgres
    env_file: ".env"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./db.init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./storage/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-net
  keycloak:
    platform: linux/amd64
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: 'keycloak'
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./storage/keycloak:/opt/keycloak/data/h2
    networks:
      - app-net
  consul:
    image: bitnami/consul:1.21.0
    container_name: 'consul'
    ports:
      - "8500:8500"
      - "8400:8400"
      - "8600:8600"
    environment:
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul
    volumes:
      - ./storage/consul:/bitnami
    networks:
      - app-net