apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streams.fullname" . }}
  labels:
    {{- include "streams.labels" . | nindent 4 }}
data:
  # Example: Generic key-value pairs from .Values.config
    # Note: We process database_url separately below using tpl
    {{- range $key, $value := .Values.config }}
    {{- if ne $key "database_url" }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}

    KAFKA_URL: {{ tpl .Values.config.kafka_url . | quote }}