server:
  port: 8070
spring:
  application:
    name: oauth2-proxy
  cloud:
    consul:
      enabled: false
    gateway:
      proxy:
        sensitive: []
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_URI}
management:
  zipkin:
    tracing:
      endpoint:  ${ZIPKIN_ENDPOINT}
  tracing:
    enabled: false
    sampling:
      probability: 1 # Сэмплируем все запросы
logging:
  level:
    org:
      springframework:
        security: DEBUG