server:
  port: 8070
upstream-uri: ${UPSTREAM_URI}
spring:
  application:
    name: oauth2-proxy
  cloud:
    consul:
      enabled: false
    gateway:
      proxy:
        sensitive: []
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_URI}
        registration:
          default:
            provider: keycloak
            client-id: ${SPRING_CLIENT_ID}
            client-secret: ${SPRING_CLIENT_SECRET}
            scope: profile
            authorization-grant-type: client_credentials
management:
  zipkin:
    tracing:
      endpoint:  ${ZIPKIN_ENDPOINT}
  tracing:
    enabled: true
    sampling:
      probability: 1 # Сэмплируем все запросы
logging:
  level:
    org:
      springframework:
        security: DEBUG