server:
  port: 8070
upstream-uri: http://localhost:9010
client-id: blocker
spring:
  application:
    name: oauth2-proxy
  cloud:
    consul:
      enabled: false
    gateway:
      proxy:
        sensitive: []
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/bank/protocol/openid-connect/token
        registration:
          blocker:
            provider: keycloak
            client-id: blocker
            client-secret: 2wSCmpPd2wlXWO5LgZV3JTQ2njtqhOQq
            scope: profile
            authorization-grant-type: client_credentials
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
logging:
  level:
    org:
      springframework:
        security: DEBUG