server:
  port: 9090
clients:
  accounts:
    uri: http://localhost:9000
  blocker:
    uri: http://localhost:9010
  notifications:
    uri: http://localhost:9020
  exchange:
    uri: http://localhost:9060
spring:
  application:
    name: accounts
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/transfers
    username: test
    password: test
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/transfers
    user: test
    password: test
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/bank/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      client-id: transfer
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1