server:
  port: 9090
clients:
  accounts:
    uri: ${GATEWAY_URL}/accounts
  blocker:
    uri: ${GATEWAY_URL}/blocker
  notifications:
    uri: ${GATEWAY_URL}/notifications
  exchange:
    uri: ${GATEWAY_URL}/exchange
spring:
  application:
    name: transfer
  cloud:
    consul:
      enabled: false
  r2dbc:
    url: r2dbc:${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG