server:
  port: 80
clients:
  accounts:
    uri: ${gateway_service_url}/accounts
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: front
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
      config:
        enabled: false
