server:
  port: 80
clients:
  accounts:
    uri: http://localhost:9000
  exchange:
    uri: http://localhost:9000/exchange
  cash:
    uri: http://localhost:9000/cash
  transfer:
    uri: http://localhost:9000/transfer
