server:
  port: 80
clients:
  accounts:
    uri: ${gateway_service_url}/accounts
spring:
  config:
    import: optional:consul:consul:8500
  cloud:
    consul:
      host: consul
      port: 8500
  application:
    name: front
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://${keycloak_url}/realms/bank/protocol/openid-connect/token
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: ${gateway_secret}
            scope: profile
            authorization-grant-type: client_credentials
