server:
  port: 80
clients:
  accounts:
    uri: ${GATEWAY_URL}/accounts
  exchange:
    uri: ${GATEWAY_URL}/exchange
  cash:
    uri: ${GATEWAY_URL}/cash
  transfer:
    uri: ${GATEWAY_URL}/transfer
spring:
  application:
    name: front
  cloud:
    consul:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_URL}
management:
  zipkin:
    tracing:
      endpoint:  ${ZIPKIN_ENDPOINT}
  tracing:
    enabled: true
    sampling:
      probability: 1 # Сэмплируем все запросы