apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash.fullname" . }}
  labels:
    {{- include "cash.labels" . | nindent 4 }}
data:
  # Example: Generic key-value pairs from .Values.config
  # Note: We process database_url separately below using tpl
  {{- range $key, $value := .Values.config }}
  {{- if ne $key "database_url" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  SPRING_DATASOURCE_URL: {{ tpl .Values.config.database_url . | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.database_username | quote }}
  KEYCLOAK_URL: {{ tpl .Values.config.keycloak_url . | quote }}
  GATEWAY_URL: {{ tpl .Values.config.gateway_url . | quote }}
  KAFKA_URL: {{ tpl .Values.config.kafka_url . | quote }}
  ZIPKIN_ENDPOINT: {{ tpl .Values.config.zipkin_endpoint . | quote }}