server:
  port: 8090
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://${keycloak_url}/realms/master/protocol/openid-connect/token
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client-id
            client-secret: uMbEKicRQZ6lxCyFz51Ol0nUPZk7BXd9
            scope: profile
            authorization-grant-type: client_credentials
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
      config:
        enabled: false
    gateway:
      routes:
        - id: to-accounts
          uri: http://localhost:9000
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
            - name: TokenRelayKeycloak
              args:
                registrationId: gateway-client
logging:
  level:
    org:
      springframework:
        security: DEBUG