server:
  port: 8090
spring:
  application:
    name: gateway
  security:
    config:
      import: optional:file:.env[.properties]
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client-id
            client-secret: uMbEKicRQZ6lxCyFz51Ol0nUPZk7BXd9
            scope: user.read
            authorization-grant-type: client_credentials
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: to-accounts
          uri: http://localhost:9000
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
            - name: TokenRelayKeycloak
              args:
                registrationId: gateway-client
logging:
  level:
    org:
      springframework:
        security: DEBUG