server:
  port: 9050
clients:
  accounts:
    uri: ${gateway_service_url}/accounts
  blocker:
    uri: ${gateway_service_url}/blocker
  notifications:
    uri: ${gateway_service_url}/notifications
spring:
  config:
    import: optional:consul:consul:8500
  cloud:
    consul:
      host: consul
      port: 8500
  application:
    name: cash
  r2dbc:
    url: r2dbc:postgresql://${pg_url}/cash
    username: ${pg_user}
    password: ${pg_password}
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:postgresql://${pg_url}/cash
    user: ${pg_user}
    password: ${pg_password}
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${keycloak_url}/realms/bank/protocol/openid-connect/certs