server:
  port: 9050
clients:
  accounts:
    uri: http://localhost:8090/accounts
  blocker:
    uri: http://localhost:9010
  notifications:
    uri: http://localhost:9020
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: cash
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/cash
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/cash
    user: ${PG_USER}
    password: ${PG_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
  cloud:
    consul:
      host: localhost
      port: 8500
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG