server:
  port: 9000
spring:
  application:
    name: accounts
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/accounts
    username: test
    password: test
  liquibase:
    url: jdbc:postgresql://localhost:5432/accounts
    user: test
    password: test
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/bank/protocol/openid-connect/certs
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1