apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "notifications.fullname" . }}
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
data:
  password: {{ .Values.config.mail_password | b64enc | quote }}

