apiVersion: v2
name: bank-app
description: Umbrella chart for bank microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: keycloak
    version: "24.3.0" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"

  - name: accounts
    version: "0.1.0"
    repository: "file://./charts/accounts" # Local path reference

  - name: oauth2proxy
    version: "0.1.0"
    alias: accounts-proxy # Alias to distinguish this instanc
    repository: "file://./charts/oauth2proxy" # Local path reference

  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: accounts-db # Alias to distinguish this instance
    condition: accounts-db.enabled # Allow disabling if needed

  - name: blocker
    version: "0.1.0"
    repository: "file://./charts/blocker" # Local path reference

  - name: oauth2proxy
    version: "0.1.0"
    alias: blocker-proxy # Alias to distinguish this instanc
    repository: "file://./charts/oauth2proxy" # Local path reference


  - name: exchange
    version: "0.1.0"
    repository: "file://./charts/exchange" # Local path reference

  - name: oauth2proxy
    version: "0.1.0"
    alias: exchange-proxy # Alias to distinguish this instanc
    repository: "file://./charts/oauth2proxy" # Local path reference

  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: exchange-db # Alias to distinguish this instance
    condition: exchange-db.enabled # Allow disabling if needed

  - name: notifications
    version: "0.1.0"
    repository: "file://./charts/notifications" # Local path reference

  - name: oauth2proxy
    version: "0.1.0"
    alias: notifications-proxy # Alias to distinguish this instanc
    repository: "file://./charts/oauth2proxy" # Local path reference

  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: notifications-db # Alias to distinguish this instance
    condition: notifications-db.enabled # Allow disabling if needed


  - name: cash
    version: "0.1.0"
    repository: "file://./charts/cash" # Local path reference

  - name: oauth2proxy
    version: "0.1.0"
    alias: cash-proxy # Alias to distinguish this instanc
    repository: "file://./charts/oauth2proxy" # Local path reference

  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: cash-db # Alias to distinguish this instance
    condition: cash-db.enabled # Allow disabling if needed

  - name: transfer
    version: "0.1.0"
    repository: "file://./charts/transfer" # Local path reference

  - name: oauth2proxy
    version: "0.1.0"
    alias: transfer-proxy # Alias to distinguish this instanc
    repository: "file://./charts/oauth2proxy" # Local path reference

  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: transfer-db # Alias to distinguish this instance
    condition: transfer-db.enabled # Allow disabling if needed

  - name: front
    version: "0.1.0"
    repository: "file://./charts/front" # Local path reference