apiVersion: v2
name: bank-app
description: Umbrella chart for bank microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: accounts
    version: "0.1.0"
    repository: "file://./charts/accounts" # Local path reference

  - name: oauth2proxy
    version: "0.1.0"
    alias: accounts-proxy # Alias to distinguish this instanc
    repository: "file://./charts/oauth2proxy" # Local path reference

  - name: postgresql
    version: "14.2.3" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"
    alias: accounts-db # Alias to distinguish this instance
    condition: accounts-db.enabled # Allow disabling if needed

  - name: keycloak
    version: "24.3.0" # Using a specific known stable version from Bitnami history
    repository: "https://charts.bitnami.com/bitnami"