global:
  domain: bank.app # Example domain for ingress

replicaCount: 1

keycloak:
  image:
    tag: "26.2.4" #default image crashes on m4
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    auth:
      username: keycloak
      database: keycloak
      password: keycloak
  volumes:
    - ./configurations:/opt/bitnami/keycloak/data/import
  service:
    type: ClusterIP
    port: 8080 # Default port, overridden by umbrella

  ingress:
    enabled: true
    ingressClassName: "nginx"
    path: /
    hostname: bank-app-keycloak
accounts:
  replicaCount: 1
  image:
    # --- REVERTED TO LOCAL REPO ---
    repository: laurkan/accounts # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
    # -----------------------------
  service:
    type: ClusterIP
    port: 9000
  ingress:
    enabled: false
#    className: "nginx"
#    hosts:
#      - host: accounts.test.local
#        paths:
#          - path: /
#            pathType: Prefix
#    tls: [ ]
  config:
    # --- CORRECTED DB URL --- Using '<ReleaseName>-<Alias>' service name convention
    database_url: "postgresql://{{ .Release.Name }}-accounts-db:5432/accounts"
    # Secret reference for password is more secure
    database_username: "accounts"
    keycloak_url: "http://{{ .Release.Namespace }}-keycloak:80"


accounts-db:
  enabled: true
  # Override values from the official postgresql chart
  auth:
    database: accounts
    username: accounts
    # Use existingSecret or provide password (less secure for production)
    # existingSecret: "{{ .Release.Name }}-customer-db-postgresql" # Name of the secret to use/create
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

accounts-proxy:
  service:
    portNumber: 9000
  ingress:
    enabled: true
    className: "nginx"
    path: /
    pathType: Prefix
    hosts:
      - accounts.test.local
  config:
    clientID: accounts
    clientSecret: GHGs7pGPlnRk8NCLI9fY7UiJ9u0uDUzU
    cookieSecret: 6oNHGunkngh3g8doPS9nbGSgkuyW37pyarG_BoexLI4=
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "http://bank-app-accounts:9000" ] #set upstreams[] to match the backend service you want to protect
  extraArgs:
    provider: keycloak-oidc
    oidc-issuer-url: "http://{{ .Release.Name }}-keycloak/realms/bank"
    cookie-secret: 6oNHGunkngh3g8doPS9nbGSgkuyW37pyarG_BoexLI4=
    skip-jwt-bearer-tokens: true
    silence-ping-logging: true
    auth-logging: true
    set-xauthrequest: true
    set-authorization-header: true
    pass-authorization-header: true
    pass-access-token: true
    show-debug-on-error: true
    errors-to-info-log: true
    cookie-httponly: false
    insecure-oidc-allow-unverified-email: true
    force-json-errors: true
    redis-insecure-skip-tls-verify: true
    #insecure-oidc-skip-issuer-verification: true