global:
  domain: bank.app # Example domain for ingress

keycloak:
  image:
    tag: "26.2.4" #default image crashes on m4
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    auth:
      username: keycloak
      database: keycloak
      password: keycloak
  volumes:
    - ./configurations:/opt/bitnami/keycloak/data/import
  service:
    type: ClusterIP
    port: 8080 # Default port, overridden by umbrella

  ingress:
    enabled: true
    ingressClassName: "nginx"
    path: /
    hostname: bank-app-keycloak

accounts:
  replicaCount: 1
  image:
    repository: laurkan/accounts # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
  service:
    type: ClusterIP
    port: 9000
  config:
    database_url: "postgresql://{{ .Release.Name }}-accounts-db:5432/accounts"
    database_username: "accounts"
    keycloak_url: http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/certs


accounts-db:
  enabled: true
  auth:
    database: accounts
    username: accounts
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

accounts-proxy:
  service:
    port: 8070
  image:
    repository: laurkan/oauth2-proxy
    tag: "latest"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    hosts:
      - host: ingress-nginx-controller.ingress-nginx
        paths:
          - path: /accounts(/|$)(.*)
            pathType: Prefix
      - host: bank.test.local
        paths:
          - path: /accounts(/|$)(.*)
            pathType: Prefix
    tls: []
  config:
    clientId: accounts
    clientSecret: GHGs7pGPlnRk8NCLI9fY7UiJ9u0uDUzU
    upstream_uri: "http://{{ .Release.Name }}-accounts:9000"
    keycloak_uri: "http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/token"

blocker:
  replicaCount: 1
  image:
    repository: laurkan/blocker # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
  service:
    type: ClusterIP
    port: 9010
  config:
    keycloak_url: http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/certs

blocker-proxy:
  service:
    port: 8070
  image:
    repository: laurkan/oauth2-proxy
    tag: "latest"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    hosts:
      - host: ingress-nginx-controller.ingress-nginx
        paths:
          - path: /blocker(/|$)(.*)
            pathType: Prefix
      - host: bank.test.local
        paths:
          - path: /blocker(/|$)(.*)
            pathType: Prefix
    tls: []
  config:
    clientId: blocker
    clientSecret: QIITHOGgLL83pJ6mLsjdqfbHgULivPUs
    upstream_uri: "http://{{ .Release.Name }}-blocker:9010"
    keycloak_uri: "http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/token"

exchange:
  replicaCount: 1
  image:
    repository: laurkan/exchange # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
  service:
    type: ClusterIP
    port: 9060
  config:
    database_url: "postgresql://{{ .Release.Name }}-exchange-db:5432/exchange"
    database_username: "exchange"
    keycloak_url: http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/certs


exchange-db:
  enabled: true
  auth:
    database: exchange
    username: exchange
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

exchange-proxy:
  service:
    port: 8070
  image:
    repository: laurkan/oauth2-proxy
    tag: "latest"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    hosts:
      - host: ingress-nginx-controller.ingress-nginx
        paths:
          - path: /exchange(/|$)(.*)
            pathType: Prefix
      - host: bank.test.local
        paths:
          - path: /exchange(/|$)(.*)
            pathType: Prefix
    tls: []
  config:
    clientId: exchange
    clientSecret: FL3OooGbSRgtd9V5reCrMSP0zzARaABc
    upstream_uri: "http://{{ .Release.Name }}-exchange:9060"
    keycloak_uri: "http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/token"

exchangegenerator:
  replicaCount: 1
  image:
    repository: laurkan/exchange-generator # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
  service:
    type: ClusterIP
    port: 9070
  config:
    gateway_url: "http://ingress-nginx-controller.ingress-nginx"
    keycloak_url: "http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/certs"

notifications:
  replicaCount: 1
  image:
    repository: laurkan/notifications # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
  service:
    type: ClusterIP
    port: 9020
  config:
    database_url: "postgresql://{{ .Release.Name }}-notifications-db:5432/notifications"
    database_username: "notifications"
    keycloak_url: http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/certs
    mail_username: kanya384@mail.ru
    mail_password: up1qKNZxxRHAnSKs0GXs # move to secrets


notifications-db:
  enabled: true
  auth:
    database: notifications
    username: notifications
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

notifications-proxy:
  service:
    port: 8070
  image:
    repository: laurkan/oauth2-proxy
    tag: "latest"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    hosts:
      - host: ingress-nginx-controller.ingress-nginx
        paths:
          - path: /notifications(/|$)(.*)
            pathType: Prefix
      - host: bank.test.local
        paths:
          - path: /notifications(/|$)(.*)
            pathType: Prefix
    tls: []
  config:
    clientId: notifications
    clientSecret: kgijylmvKjrEuk2wIXi3GmA4u30iFFkD
    upstream_uri: "http://{{ .Release.Name }}-notifications:9020"
    keycloak_uri: "http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/token"

cash:
  replicaCount: 1
  image:
    repository: laurkan/cash # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
  service:
    type: ClusterIP
    port: 9050
  config:
    database_url: "postgresql://{{ .Release.Name }}-cash-db:5432/cash"
    database_username: "cash"
    keycloak_url: http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/certs
    gateway_url: "http://ingress-nginx-controller.ingress-nginx"


cash-db:
  enabled: true
  auth:
    database: cash
    username: cash
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

cash-proxy:
  service:
    port: 8070
  image:
    repository: laurkan/oauth2-proxy
    tag: "latest"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    hosts:
      - host: ingress-nginx-controller.ingress-nginx
        paths:
          - path: /cash(/|$)(.*)
            pathType: Prefix
      - host: bank.test.local
        paths:
          - path: /cash(/|$)(.*)
            pathType: Prefix
    tls: []
  config:
    clientId: cash
    clientSecret: dMI5HAyzkdvkyPVXV5ijGMeHwqNHOSPt
    upstream_uri: "http://{{ .Release.Name }}-cash:9050"
    keycloak_uri: "http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/token"