global:
  domain: bank.app # Example domain for ingress

replicaCount: 1

keycloak:
  image:
    tag: "26.2.4" #default image crashes on m4
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    auth:
      username: keycloak
      database: keycloak
      password: keycloak
  volumes:
    - ./configurations:/opt/bitnami/keycloak/data/import
  service:
    type: ClusterIP
    port: 8080 # Default port, overridden by umbrella

  ingress:
    enabled: true
    ingressClassName: "nginx"
    path: /
    hostname: bank-app-keycloak
accounts:
  replicaCount: 1
  image:
    # --- REVERTED TO LOCAL REPO ---
    repository: laurkan/accounts # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
    # -----------------------------
  service:
    type: ClusterIP
    port: 9000
  ingress:
    enabled: false
#    className: "nginx"
#    hosts:
#      - host: accounts.test.local
#        paths:
#          - path: /
#            pathType: Prefix
#    tls: [ ]
  config:
    # --- CORRECTED DB URL --- Using '<ReleaseName>-<Alias>' service name convention
    database_url: "postgresql://{{ .Release.Name }}-accounts-db:5432/accounts"
    # Secret reference for password is more secure
    database_username: "accounts"
    keycloak_url: "http://{{ .Release.Namespace }}-keycloak:80"


accounts-db:
  enabled: true
  # Override values from the official postgresql chart
  auth:
    database: accounts
    username: accounts
    # Use existingSecret or provide password (less secure for production)
    # existingSecret: "{{ .Release.Name }}-customer-db-postgresql" # Name of the secret to use/create
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

oauth2proxy:
  image:
    repository: laurkan/oauth2-proxy
    tag: "latest"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Upstream-Uri: http://bank-app-$1:9000";
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: bank.test.local
        paths:
          - path: /accounts
            pathType: Prefix
    tls: [ ]
  config:
    clients:
      - clientId: accounts
        clientSecret: ejaCcoPlhth94SVjHB3qzplsj6eMVPO3
    upstream_uri: "http://{{ .Release.Namespace }}-keycloak:80"
    keycloak_uri: "http://{{ .Release.Namespace }}-keycloak:80"