global:
  domain: bank.app # Example domain for ingress

replicaCount: 1

keycloak:
  image:
    tag: "26.2.4" #default image crashes on m4
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    auth:
      username: keycloak
      database: keycloak
      password: keycloak
  volumes:
    - ./configurations:/opt/bitnami/keycloak/data/import
  service:
    type: ClusterIP
    port: 8080 # Default port, overridden by umbrella

  ingress:
    enabled: true
    ingressClassName: "nginx"
    path: /
    hostname: bank-app-keycloak
accounts:
  replicaCount: 1
  image:
    # --- REVERTED TO LOCAL REPO ---
    repository: laurkan/accounts # Removed registry prefix
    tag: "latest"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
    # -----------------------------
  service:
    type: ClusterIP
    port: 9000
  config:
    database_url: "postgresql://{{ .Release.Name }}-accounts-db:5432/accounts"
    database_username: "accounts"
    keycloak_url: http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/certs


accounts-db:
  enabled: true
  auth:
    database: accounts
    username: accounts
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example

accounts-proxy:
  service:
    port: 8070
  image:
    repository: laurkan/oauth2-proxy
    tag: "latest"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    hosts:
      - host: bank.test.local
        paths:
          - path: /accounts(/|$)(.*)
            pathType: Prefix
    tls: []
  config:
    clientId: accounts
    clientSecret: GHGs7pGPlnRk8NCLI9fY7UiJ9u0uDUzU
    upstream_uri: "http://{{ .Release.Name }}-accounts:9000"
    keycloak_uri: "http://{{ .Release.Name }}-keycloak/realms/bank/protocol/openid-connect/token"