server:
  port: 1000
spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: streams
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans