apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchangegenerator.fullname" . }}
  labels:
    {{- include "exchangegenerator.labels" . | nindent 4 }}
data:
  # Example: Generic key-value pairs from .Values.config
  # Note: We process database_url separately below using tpl
  {{- range $key, $value := .Values.config }}
  {{- if ne $key "database_url" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  # Example: How Spring Boot might consume DB config (adjust keys as needed)
  # Ensure these keys match what your application expects.
  # Note: The values come from .Values.config which are set by the umbrella chart.
  # Use the 'tpl' function to render the database_url which contains Helm templating itself
  KEYCLOAK_URL: {{ tpl .Values.config.keycloak_url . | quote }}
  GATEWAY_URL: {{ tpl .Values.config.gateway_url . | quote }}
  KAFKA_PRODUCER_URL: {{ tpl .Values.config.kafka_producer_url . | quote }}
  # SPRING_DATASOURCE_PASSWORD would typically come from a secret, not this ConfigMap.

  # Example: Include other config defined in values.yaml
  # OTHER_CONFIG_PARAM: {{ .Values.config.some_other_config | quote }}