server:
  port: 9070
spring:
  cloud:
    consul:
      enabled: false
  application:
    name: exchange-generator
  kafka:
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
      bootstrap-servers: ${KAFKA_URL}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
      acks: 0 #at most one delivery