server:
  port: 9070
clients:
  exchange:
    uri: http://localhost:9060
spring:
  application:
    name: exchange-rates
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs