server:
  port: 9070
clients:
  exchange:
    uri: ${gateway_service_url}/exchange
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak_url}/realms/master/protocol/openid-connect/certs
  cloud:
    consul:
      host: ${consul_host}
      port: ${consul_port}
      config:
        enabled: false