server:
  port: 9070
clients:
  exchange:
    uri: http://localhost:9060
spring:
  application:
    name: exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
  cloud:
    consul:
      host: localhost
      port: 8500