server:
  port: 9070
spring:
  application:
    name: exchange-generator
  cloud:
    consul:
      enabled: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 0 #at most one delivery
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
logging:
  level:
    ru.laurkan.bank: DEBUG