server:
  port: 9070
clients:
  exchange:
    uri: ${gateway_service_url}/exchange
spring:
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
  application:
    name: exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak_url}/realms/master/protocol/openid-connect/certs