server:
  port: 9070
clients:
  exchange:
    uri: ${GATEWAY_URL}/exchange
spring:
  cloud:
    consul:
      enabled: false
  application:
    name: exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}