server:
  port: 9070
clients:
  exchange:
    uri: ${gateway_service_url}/exchange
spring:
  application:
    name: exchange-generator
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${keycloak_url}/realms/master/protocol/openid-connect/certs
  cloud:
    consul:
      host: consul
      port: 8500