server:
  port: 9070
clients:
  exchange:
    uri: http://localhost:9060
spring:
  application:
    name: exchange-generator
  cloud:
    consul:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs