apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "oauth2proxy.fullname" . }}
  labels:
    {{- include "oauth2proxy.labels" . | nindent 4 }}
data:
  {{- range $index, $client := .Values.config.clients }}
  {{ $client.clientId }}-secret: {{ $client.clientSecret | b64enc | quote }}
  {{- end }}

