apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "oauth2proxy.fullname" . }}
  labels:
    {{- include "oauth2proxy.labels" . | nindent 4 }}
data:
  client-secret: {{ .Values.config.clientSecret | b64enc | quote }}

