apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "oauth2proxy.fullname" . }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "oauth2proxy.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s