server:
  port: 9020
mail:
  username: test
  password: test
  smtp:
    host: smtp.mail.ru
    port: 465
spring:
  application:
    name: accounts
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/notifications
    username: test
    password: test
  jpa:
    show-sql: true
  cloud:
    consul:
      enabled: false
  liquibase:
    url: jdbc:postgresql://localhost:5432/notifications
    user: test
    password: test
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/bank/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: "ru.laurkan.bank.events.*"
      group-id: notifications-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer