apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts.fullname" . }}
  labels:
    {{- include "accounts.labels" . | nindent 4 }}
data:
  # Example: Generic key-value pairs from .Values.config
  # Note: We process database_url separately below using tpl
  {{- range $key, $value := .Values.config }}
  {{- if ne $key "database_url" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  # Example: How Spring Boot might consume DB config (adjust keys as needed)
  # Ensure these keys match what your application expects.
  # Note: The values come from .Values.config which are set by the umbrella chart.
  # Use the 'tpl' function to render the database_url which contains Helm templating itself
  SPRING_DATASOURCE_URL: {{ tpl .Values.config.database_url . | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.database_username | quote }}
  KEYCLOAK_URL: {{ tpl .Values.config.keycloak_url . | quote }}
  KAFKA_URL: {{ tpl .Values.config.kafka_url . | quote }}
  ZIPKIN_ENDPOINT: {{ tpl .Values.config.zipkin_endpoint . | quote }}