server:
  port: 9060
spring:
  application:
    name: exchange
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: test
    password: test
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/test
    user: test
    password: test
    change-log: classpath:/db/changelog/db.changelog-master.xml
  cloud:
    consul:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/bank/protocol/openid-connect/certs
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "ru.laurkan.bank.events.*"
      bootstrap-servers: localhost:9092
      group-id: exchange
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans