server:
  port: 9060
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: exchange
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/exchange_rates
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    show-sql: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/exchange_rates
    user: ${PG_USER}
    password: ${PG_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs